# Generated by Django 5.1 on 2026-02-19 05:27

import core.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(blank=True, help_text='Comma-separated list of ingredients')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('suitable_skin_type', models.CharField(choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('all', 'All Skin Types')], db_index=True, help_text='AI le yesबाट match garcha', max_length=20)),
                ('skin_concern', models.CharField(choices=[('acne', 'Acne & Blemishes'), ('aging', 'Anti-Aging & Wrinkles'), ('brightening', 'Brightening & Glow'), ('hydration', 'Hydration & Moisture'), ('pigmentation', 'Dark Spots & Pigmentation'), ('sensitivity', 'Redness & Sensitivity'), ('general', 'General Skincare')], db_index=True, default='general', max_length=20)),
                ('min_age', models.PositiveIntegerField(help_text='Minimum recommended age', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.PositiveIntegerField(help_text='Maximum recommended age', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], db_index=True, default='unisex', max_length=10)),
                ('image', models.ImageField(help_text='Main product image', upload_to=core.utils.generate_unique_filename)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=core.utils.generate_unique_filename)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=core.utils.generate_unique_filename)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Stock yo bhandaa kam bhayo bhane alert')),
                ('is_featured', models.BooleanField(default=False, help_text='Homepage ma featured product')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Kati jana le heryo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['suitable_skin_type'], name='products_pr_suitabl_a5e3b8_idx'), models.Index(fields=['gender'], name='products_pr_gender_b0135f_idx'), models.Index(fields=['skin_concern'], name='products_pr_skin_co_62baf1_idx'), models.Index(fields=['min_age', 'max_age'], name='products_pr_min_age_4c498a_idx'), models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx'), models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx')],
            },
        ),
    ]
