# add_products_only.py
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.development')
django.setup()

from apps.products.models import Category, Product

def create_products():
    """Create 20 products"""
    
    # Get existing categories
    try:
        moisturizer = Category.objects.get(name='Moisturizer')
        sunscreen = Category.objects.get(name='Sunscreen')
        serum = Category.objects.get(name='Serum')
        cleanser = Category.objects.get(name='Cleanser')
        toner = Category.objects.get(name='Toner')
        mask = Category.objects.get(name='Face Mask')
        print("✅ All categories found!")
    except Category.DoesNotExist as e:
        print(f"❌ Error: Category not found - {e}")
        print("Please create all 6 categories first!")
        return
    
    products_data = [
        {
            'name': 'Himalaya Herbals Nourishing Skin Cream',
            'brand': 'Himalaya',
            'category': moisturizer,
            'description': 'Rich moisturizing cream with natural ingredients. Provides 24-hour hydration for dry and sensitive skin.',
            'ingredients': 'Aloe Vera, Winter Cherry, Vitamin E, Natural Oils',
            'price': 599,
            'discount_percent': 10,
            'suitable_skin_type': 'dry',
            'skin_concern': 'hydration',
            'min_age': 18,
            'max_age': 60,
            'gender': 'unisex',
            'stock': 50,
            'is_featured': True,
        },
        {
            'name': 'Neutrogena Oil-Free Acne Wash',
            'brand': 'Neutrogena',
            'category': cleanser,
            'description': 'Deep cleansing face wash specially formulated for oily and acne-prone skin.',
            'ingredients': 'Salicylic Acid, Glycerin, Purified Water',
            'price': 399,
            'discount_percent': 15,
            'suitable_skin_type': 'oily',
            'skin_concern': 'acne',
            'min_age': 15,
            'max_age': 40,
            'gender': 'unisex',
            'stock': 80,
            'is_featured': True,
        },
        {
            'name': 'Lotus Herbals Safe Sun UV Screen SPF 50',
            'brand': 'Lotus Herbals',
            'category': sunscreen,
            'description': 'Broad spectrum sunscreen with SPF 50 PA+++. Protects from harmful UVA and UVB rays.',
            'ingredients': 'Zinc Oxide, Vitamin E, Aloe Vera',
            'price': 650,
            'discount_percent': 0,
            'suitable_skin_type': 'all',
            'skin_concern': 'general',
            'min_age': 10,
            'max_age': 70,
            'gender': 'unisex',
            'stock': 100,
            'is_featured': True,
        },
        {
            'name': 'Olay Regenerist Retinol 24 Serum',
            'brand': 'Olay',
            'category': serum,
            'description': 'Advanced anti-aging night serum with retinol and niacinamide.',
            'ingredients': 'Retinol, Niacinamide, Vitamin B3, Hyaluronic Acid',
            'price': 1299,
            'discount_percent': 20,
            'suitable_skin_type': 'normal',
            'skin_concern': 'aging',
            'min_age': 30,
            'max_age': 65,
            'gender': 'female',
            'stock': 40,
            'is_featured': True,
        },
        {
            'name': 'Cetaphil Moisturizing Lotion',
            'brand': 'Cetaphil',
            'category': moisturizer,
            'description': 'Gentle, non-comedogenic moisturizer for sensitive skin.',
            'ingredients': 'Glycerin, Vitamin E, Natural Emollients',
            'price': 799,
            'discount_percent': 5,
            'suitable_skin_type': 'sensitive',
            'skin_concern': 'sensitivity',
            'min_age': 15,
            'max_age': 60,
            'gender': 'unisex',
            'stock': 60,
            'is_featured': True,
        },
        {
            'name': 'Plum Green Tea Alcohol-Free Toner',
            'brand': 'Plum',
            'category': toner,
            'description': 'Refreshing toner with green tea extract. Removes impurities and provides natural glow.',
            'ingredients': 'Green Tea Extract, Glycolic Acid, Witch Hazel',
            'price': 449,
            'discount_percent': 10,
            'suitable_skin_type': 'combination',
            'skin_concern': 'brightening',
            'min_age': 20,
            'max_age': 45,
            'gender': 'female',
            'stock': 70,
            'is_featured': False,
        },
        {
            'name': 'The Body Shop Vitamin E Overnight Mask',
            'brand': 'The Body Shop',
            'category': mask,
            'description': 'Intensely hydrating overnight face mask. Locks in moisture for 24 hours.',
            'ingredients': 'Vitamin E, Hyaluronic Acid, Wheat Germ Oil',
            'price': 1095,
            'discount_percent': 15,
            'suitable_skin_type': 'dry',
            'skin_concern': 'hydration',
            'min_age': 18,
            'max_age': 50,
            'gender': 'unisex',
            'stock': 30,
            'is_featured': False,
        },
        {
            'name': 'Garnier Men Turbo Light Oil Control',
            'brand': 'Garnier',
            'category': cleanser,
            'description': 'Deep cleansing face wash for men with oily skin. Controls shine and removes excess oil.',
            'ingredients': 'Charcoal, Menthol, Glycerin',
            'price': 299,
            'discount_percent': 0,
            'suitable_skin_type': 'oily',
            'skin_concern': 'general',
            'min_age': 18,
            'max_age': 50,
            'gender': 'male',
            'stock': 90,
            'is_featured': False,
        },
        {
            'name': 'Lakme Absolute Perfect Radiance Serum',
            'brand': 'Lakme',
            'category': serum,
            'description': 'Intensive dark spot corrector serum. Reduces pigmentation and brightens skin tone.',
            'ingredients': 'Niacinamide, Vitamin C, Licorice Extract',
            'price': 875,
            'discount_percent': 12,
            'suitable_skin_type': 'normal',
            'skin_concern': 'pigmentation',
            'min_age': 25,
            'max_age': 55,
            'gender': 'female',
            'stock': 50,
            'is_featured': False,
        },
        {
            'name': 'Simple Kind to Skin Hydrating Light Moisturizer',
            'brand': 'Simple',
            'category': moisturizer,
            'description': 'Lightweight moisturizer for combination skin. Balances oil and hydration.',
            'ingredients': 'Glycerin, Vitamin E, Pro-Vitamin B5',
            'price': 549,
            'discount_percent': 8,
            'suitable_skin_type': 'combination',
            'skin_concern': 'hydration',
            'min_age': 20,
            'max_age': 45,
            'gender': 'unisex',
            'stock': 65,
            'is_featured': False,
        },
        {
            'name': 'Minimalist Salicylic Acid 2% Serum',
            'brand': 'Minimalist',
            'category': serum,
            'description': 'Potent acne treatment serum with 2% salicylic acid. Unclogs pores and reduces breakouts.',
            'ingredients': 'Salicylic Acid 2%, Zinc PCA, Hyaluronic Acid',
            'price': 499,
            'discount_percent': 0,
            'suitable_skin_type': 'oily',
            'skin_concern': 'acne',
            'min_age': 16,
            'max_age': 35,
            'gender': 'unisex',
            'stock': 45,
            'is_featured': True,
        },
        {
            'name': 'La Roche-Posay Anthelios Oil Control SPF 50+',
            'brand': 'La Roche-Posay',
            'category': sunscreen,
            'description': 'Mattifying sunscreen for oily and acne-prone skin. Oil-free, non-comedogenic formula.',
            'ingredients': 'Mexoryl XL, Airlicium Technology, Thermal Spring Water',
            'price': 1450,
            'discount_percent': 10,
            'suitable_skin_type': 'oily',
            'skin_concern': 'general',
            'min_age': 15,
            'max_age': 50,
            'gender': 'unisex',
            'stock': 35,
            'is_featured': True,
        },
        {
            'name': 'Cosrx AHA/BHA Clarifying Treatment Toner',
            'brand': 'Cosrx',
            'category': toner,
            'description': 'Gentle daily exfoliating toner with AHA and BHA. Removes dead skin cells.',
            'ingredients': 'AHA, BHA, Mineral Water, Willow Bark Extract',
            'price': 899,
            'discount_percent': 15,
            'suitable_skin_type': 'combination',
            'skin_concern': 'acne',
            'min_age': 20,
            'max_age': 40,
            'gender': 'unisex',
            'stock': 40,
            'is_featured': False,
        },
        {
            'name': 'Innisfree Super Volcanic Pore Clay Mask',
            'brand': 'Innisfree',
            'category': mask,
            'description': 'Deep cleansing clay mask with volcanic clusters. Absorbs sebum and minimizes pores.',
            'ingredients': 'Jeju Volcanic Clusters, Kaolin Clay, AHA',
            'price': 750,
            'discount_percent': 0,
            'suitable_skin_type': 'oily',
            'skin_concern': 'acne',
            'min_age': 18,
            'max_age': 45,
            'gender': 'unisex',
            'stock': 55,
            'is_featured': False,
        },
        {
            'name': 'The Ordinary Hyaluronic Acid 2% + B5',
            'brand': 'The Ordinary',
            'category': serum,
            'description': 'Multi-depth hydration serum with pure hyaluronic acid and vitamin B5.',
            'ingredients': 'Hyaluronic Acid 2%, Vitamin B5, Aqua',
            'price': 699,
            'discount_percent': 0,
            'suitable_skin_type': 'dry',
            'skin_concern': 'hydration',
            'min_age': 18,
            'max_age': 60,
            'gender': 'unisex',
            'stock': 60,
            'is_featured': True,
        },
        {
            'name': 'Nivea Rich Nourishing Night Cream',
            'brand': 'Nivea',
            'category': moisturizer,
            'description': 'Rich night cream for very dry skin. Deeply nourishes and regenerates skin overnight.',
            'ingredients': 'Almond Oil, Vitamin E, Dexpanthenol',
            'price': 425,
            'discount_percent': 5,
            'suitable_skin_type': 'dry',
            'skin_concern': 'hydration',
            'min_age': 25,
            'max_age': 60,
            'gender': 'female',
            'stock': 75,
            'is_featured': False,
        },
        {
            'name': 'Mamaearth Vitamin C Serum',
            'brand': 'Mamaearth',
            'category': serum,
            'description': 'Natural vitamin C serum for glowing skin. Reduces dark spots and hyperpigmentation.',
            'ingredients': 'Vitamin C, Turmeric Extract, Aloe Vera',
            'price': 599,
            'discount_percent': 20,
            'suitable_skin_type': 'normal',
            'skin_concern': 'brightening',
            'min_age': 20,
            'max_age': 50,
            'gender': 'female',
            'stock': 50,
            'is_featured': True,
        },
        {
            'name': 'Neutrogena Hydro Boost Water Gel',
            'brand': 'Neutrogena',
            'category': moisturizer,
            'description': 'Oil-free gel moisturizer with hyaluronic acid. Instantly quenches dry skin.',
            'ingredients': 'Hyaluronic Acid, Glycerin, Dimethicone',
            'price': 649,
            'discount_percent': 0,
            'suitable_skin_type': 'combination',
            'skin_concern': 'hydration',
            'min_age': 18,
            'max_age': 45,
            'gender': 'unisex',
            'stock': 55,
            'is_featured': False,
        },
        {
            'name': 'Garnier Skin Naturals Micellar Water',
            'brand': 'Garnier',
            'category': cleanser,
            'description': 'All-in-one cleanser, makeup remover, and toner. Suitable for all skin types.',
            'ingredients': 'Micelles, Glycerin, Purified Water',
            'price': 350,
            'discount_percent': 10,
            'suitable_skin_type': 'all',
            'skin_concern': 'general',
            'min_age': 15,
            'max_age': 60,
            'gender': 'unisex',
            'stock': 85,
            'is_featured': False,
        },
        {
            'name': 'Wow Skin Science Vitamin C Sheet Mask Pack',
            'brand': 'Wow Skin Science',
            'category': mask,
            'description': 'Pack of 5 sheet masks infused with vitamin C and hyaluronic acid. Instant glow in 15 minutes.',
            'ingredients': 'Vitamin C, Hyaluronic Acid, Niacinamide',
            'price': 499,
            'discount_percent': 15,
            'suitable_skin_type': 'all',
            'skin_concern': 'brightening',
            'min_age': 18,
            'max_age': 55,
            'gender': 'female',
            'stock': 40,
            'is_featured': True,
        },
    ]
    
    created_count = 0
    skipped_count = 0
    
    for product_data in products_data:
        product, created = Product.objects.get_or_create(
            name=product_data['name'],
            defaults=product_data
        )
        if created:
            created_count += 1
            print(f"  ✅ Created: {product_data['name']}")
        else:
            skipped_count += 1
            print(f"  ⏭️  Skipped: {product_data['name']} (already exists)")
    
    print(f"\n🎉 Done!")
    print(f"  ✅ Created: {created_count} products")
    print(f"  ⏭️  Skipped: {skipped_count} products (already existed)")


if __name__ == '__main__':
    print("🚀 Starting product creation...\n")
    create_products()
    print("\n✅ Check admin panel to see your products!")