# Generated by Django 5.1 on 2026-02-19 05:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='User uploaded facial image', upload_to='skin_analysis/%Y/%m/')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination')], db_index=True, help_text='CNN model le detect gareko skin type', max_length=20, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Model confidence (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Analysis fail bhayo bhane error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Skin Analysis',
                'verbose_name_plural': 'Skin Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinFeature',
            fields=[
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='features', serialize=False, to='skin_analysis.skinanalysis')),
                ('oiliness_score', models.FloatField(default=0.0, help_text='How oily the skin is', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('dryness_score', models.FloatField(default=0.0, help_text='How dry the skin is', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('texture_density', models.FloatField(default=0.0, help_text='Skin texture roughness', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('pore_visibility', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('redness_score', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Skin Feature',
                'verbose_name_plural': 'Skin Features',
            },
        ),
    ]
