# Generated by Django 5.1 on 2026-02-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skin_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skinanalysis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional — guest users pani analyze garna sakcha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='skinanalysis',
            index=models.Index(fields=['skin_type'], name='skin_analys_skin_ty_0a4d16_idx'),
        ),
        migrations.AddIndex(
            model_name='skinanalysis',
            index=models.Index(fields=['status'], name='skin_analys_status_260550_idx'),
        ),
        migrations.AddIndex(
            model_name='skinanalysis',
            index=models.Index(fields=['user', 'created_at'], name='skin_analys_user_id_b11f8f_idx'),
        ),
    ]
