# Generated by Django 5.1 on 2026-03-31 17:14

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skinanalysis',
            name='dry_probability',
            field=models.FloatField(default=0.0, help_text='CNN raw probability for dry class (e.g. 0.2855)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='normal_probability',
            field=models.FloatField(default=0.0, help_text='CNN raw probability for normal class (e.g. 0.7137)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='oily_probability',
            field=models.FloatField(default=0.0, help_text='CNN raw probability for oily class (e.g. 0.0007)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='age',
            field=models.PositiveIntegerField(help_text='Entered manually by the user', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Probability of winning class (e.g. 0.7137 for 71.4%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Selected manually by the user', max_length=10),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='image',
            field=models.ImageField(help_text='Facial image — uploaded from device or captured via camera', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='skin_analysis/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('dry', 'Dry'), ('oily', 'Oily'), ('normal', 'Normal')], db_index=True, help_text='Winning class from CNN — dry, oily, or normal only', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for guest users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skinfeature',
            name='dryness_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skinfeature',
            name='oiliness_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skinfeature',
            name='pore_visibility',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skinfeature',
            name='redness_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skinfeature',
            name='texture_density',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
