# Generated by Django 5.1 on 2026-02-19 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Overall match score (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rank', models.PositiveIntegerField(default=0, help_text='Recommendation ranking (1st, 2nd, 3rd...)')),
                ('skin_type_match', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('age_match', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('gender_match', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reasoning', models.TextField(blank=True, help_text='Why this product was recommended')),
                ('user_feedback', models.CharField(choices=[('none', 'No Feedback'), ('liked', 'Liked'), ('disliked', 'Disliked'), ('purchased', 'Purchased')], db_index=True, default='none', max_length=20)),
                ('feedback_comment', models.TextField(blank=True, help_text='Optional user comment')),
                ('is_clicked', models.BooleanField(default=False, help_text='User le product click garyo ki nai')),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['analysis', 'rank'],
            },
        ),
    ]
