# Generated by Django 5.1 on 2026-02-19 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('skin_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recommendation_session', serialize=False, to='skin_analysis.skinanalysis')),
                ('total_products_matched', models.PositiveIntegerField(default=0)),
                ('algorithm_version', models.CharField(default='v1.0', help_text='Matching algorithm version used', max_length=50)),
                ('filters_applied', models.JSONField(default=dict, help_text='Filters used in matching')),
                ('processing_time_ms', models.PositiveIntegerField(default=0, help_text='Time taken to generate recommendations (milliseconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation Session',
                'verbose_name_plural': 'Recommendation Sessions',
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='analysis',
            field=models.ForeignKey(help_text='Source skin analysis', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='skin_analysis.skinanalysis'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(help_text='Recommended product', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['analysis', 'rank'], name='recommendat_analysi_3c7817_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['product'], name='recommendat_product_782e54_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user_feedback'], name='recommendat_user_fe_0efa2e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['match_score'], name='recommendat_match_s_aafafa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('analysis', 'product')},
        ),
    ]
