# Generated by Django 5.1 on 2026-03-31 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
        ('recommendations', '0002_initial'),
        ('skin_analysis', '0003_skinanalysis_dry_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='age_match',
            field=models.FloatField(default=0.0, help_text='Score based on user-entered age vs product age range', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='analysis',
            field=models.ForeignKey(help_text='Source skin analysis (contains ML skin_type + user age/gender)', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='skin_analysis.skinanalysis'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='gender_match',
            field=models.FloatField(default=0.0, help_text='Score based on user-entered gender vs product gender', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='match_score',
            field=models.FloatField(help_text='Overall weighted match score (0.0 – 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='Rank among recommendations for this analysis (1 = best)'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Human-readable explanation with dermatological source citations'),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='algorithm_version',
            field=models.CharField(default='v3.0-hybrid-derm-knowledge', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='filters_applied',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='processing_time_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DermaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('normal', 'Normal')], db_index=True, max_length=10)),
                ('age_group', models.CharField(choices=[('teen', 'Teen (13–17)'), ('young_adult', 'Young Adult (18–29)'), ('adult', 'Adult (30–49)'), ('mature', 'Mature (50+)')], db_index=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=10)),
                ('primary_ingredients', models.TextField(help_text='Comma-separated. JAAD/AAD validated primary ingredients. e.g. salicylic acid, niacinamide, benzoyl peroxide')),
                ('secondary_ingredients', models.TextField(blank=True, help_text='Comma-separated. Beneficial but lower priority than primary.')),
                ('avoid_ingredients', models.TextField(blank=True, help_text='Comma-separated. Products containing these get a score penalty. e.g. mineral oil for oily skin, alcohol denat for dry skin')),
                ('key_concerns', models.TextField(default='general', help_text='Comma-separated. Concern keys from Product.CONCERN_CHOICES. e.g. acne, aging, hydration, brightening')),
                ('source', models.CharField(blank=True, help_text='Citation e.g. "AAD 20s Skincare + JAAD Delphi Consensus [2,3]"', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Derma Profile',
                'verbose_name_plural': 'Derma Profiles',
                'ordering': ['skin_type', 'age_group', 'gender'],
                'indexes': [models.Index(fields=['skin_type', 'age_group', 'gender'], name='recommendat_skin_ty_cd01c2_idx')],
                'unique_together': {('skin_type', 'age_group', 'gender')},
            },
        ),
    ]
