# Generated by Django 5.1 on 2026-02-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in NPR', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('khalti_token', models.CharField(blank=True, max_length=255)),
                ('khalti_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('khalti_idx', models.CharField(blank=True, max_length=255)),
                ('payment_response', models.JSONField(blank=True, default=dict, help_text='Full payment gateway response')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'), models.Index(fields=['khalti_transaction_id'], name='payments_pa_khalti__cc46c0_idx')],
            },
        ),
    ]
